#!/bin/bash
# Usage:
#  autopkgtest-oem-scripts-auto --ssh ~/.ssh/id_ecdsa > auto-provision.sh && chmod +x auto-provision.sh

set -euo pipefail
IFS=$'\n\t'

# shellcheck source=config.sh
source /usr/share/oem-scripts/config.sh 2>/dev/null || source config.sh

# Get the path of autopkgtest-oem-scripts-auto, it's same path with launchpad-api
cur_dir=$(cd "$(dirname "$0")" || exit; pwd)

if ! valid_oem_scripts_config; then
    >&2 echo "Please execute \`launchpad-api\` to get the token for Launchpad API first."
    exit 1
fi

autopkgtest_collect_credentials="${cur_dir}/autopkgtest-collect-credentials"

${autopkgtest_collect_credentials} --git ppa:oem-solutions-group/ppa ~/.config/oem-scripts/config.ini "$@"
