#!/bin/bash

# shellcheck source=config.sh
source /usr/share/oem-scripts/config.sh 2>/dev/null || source config.sh

if ! has_oem_scripts_config; then
    echo "Please execute \`launchpad-api\` to get the token for Launchpad API first."
    exit 1
else
    oauth_token=$(read_oem_scripts_config oauth_token)
    oauth_token_secret=$(read_oem_scripts_config oauth_token_secret)
fi

PPA="ppa:oem-solutions-group/ppa"
RET=$(get-private-ppa $PPA)
NAME=$(echo "$RET" | awk '{print $1}')
URL=$(echo "$RET" | awk '{print $2}')
KEY=$(echo "$RET" | awk '{print $3}')

cat <<ENDLINE
#!/bin/sh

export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export LANGUAGE=C:

install_pkgs ()
{
    for pkg in "\$@"; do
        if ! dpkg-query -W -f='\${Status}\n' "\$pkg" | grep "install ok installed"; then
            apt-get install "\$pkg" --yes
        fi
    done
}

importkey()
{
    apt-key adv --keyserver keyserver.ubuntu.com --recv-key "\$1"
}

install_pkgs gpg apt-transport-https

importkey "$KEY"

echo "deb $URL \$(lsb_release -cs) main" > "/etc/apt/sources.list.d/$NAME-\$(lsb_release -cs).list"
echo "# deb-src $URL \$(lsb_release -cs) main" >> "/etc/apt/sources.list.d/$NAME-\$(lsb_release -cs).list"

HOME="/home/\$(grep 1000:1000 /etc/passwd | awk -F: '{print \$1}')"
mkdir -p "\$HOME/.config/oem-scripts"
echo "oauth_token = $oauth_token" > "\$HOME/.config/oem-scripts/config.ini"
echo "oauth_token_secret = $oauth_token_secret" >> "\$HOME/.config/oem-scripts/config.ini"

sudo apt-get update
ENDLINE
