#!/bin/bash

# shellcheck source=config.sh
source /usr/share/oem-scripts/config.sh 2>/dev/null || source config.sh

if ! has_config; then
    echo "Please execute \`launchpad-api.sh\` to get the token for Launchpad API first."
    exit 1
fi

PPA="$1"
GROUP=$(echo "${PPA//[:\/]/ }" | awk '{print $2}')
ARCHIVE=$(echo "${PPA//[:\/]/ }" | awk '{print $3}')

username=$(launchpad-api.sh get devel/people/+me | jq -r .name)
URL=$(launchpad-api.sh post "devel/~$username" ws.op=getArchiveSubscriptionURL "archive=https://api.launchpad.net/devel/~$GROUP/+archive/ubuntu/$ARCHIVE" | jq -r .)
KEY=$(launchpad-api.sh get "devel/~$GROUP/+archive/ubuntu/$ARCHIVE" | jq -r .signing_key_fingerprint)

echo "$URL" "$KEY"
