#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Usage:
# launchpad-api get https://api.launchpad.net/devel/~fourdollars/oem-dev-tools/+git/oem-scripts/+merge/384887
# launchpad-api get https://api.launchpad.net/devel/~fourdollars/oem-dev-tools/+git/oem-scripts/+merge/384887 | jq-lp .preview_diff_link
# launchpad-api get https://api.launchpad.net/devel/~fourdollars/oem-dev-tools/+git/oem-scripts/+merge/384887 | jq-lp .preview_diff_link | jq-lp .diff_text_link

# Get the path of jq-lp, it's same path with launchpad-api
cur_dir=$(cd "$(dirname "$0")"; pwd)
launchpad_api="${cur_dir}/launchpad-api"

while read -r api; do
    ${launchpad_api} get "$api"
done < <(jq -r "$@")
