#!/bin/bash
# https://help.launchpad.net/API/SigningRequests
# https://api.launchpad.net/
# Usage:
#  launchpad-api get devel/people/+me
#  launchpad-api get devel/people/+me ws.op==getArchiveSubscriptionURLs
# NOTE:
# When it return "HTTP/1.1 401 Unauthorized" and no URL just show "You need to be logged in to view this URL."
# Please remove the config.ini and try again.
# $ rm ~/.config/oem-scripts/config.ini

oauth_consumer_key=${oauth_consumer_key:="System-wide: $(lsb_release -is) (oem-scripts $(hostname))"}

# shellcheck source=config.sh
source /usr/share/oem-scripts/config.sh 2>/dev/null || source config.sh

http_file=$(which http)
if [ "${http_file}" = "" ] || [ ! -x ${http_file} ]; then
    echo "Please install \`httpie\` package!"
    exit 1
fi

get_token()
{
    [ "x$debug" = "x1" ] && echo "oauth_consumer_key=${oauth_consumer_key}"

    oauth=$(http --ignore-stdin --form post https://launchpad.net/+request-token oauth_consumer_key="$oauth_consumer_key" oauth_signature_method=PLAINTEXT oauth_signature="&")
    [ "x$debug" = "x1" ] && echo "$oauth"

    eval "${oauth/&*/}"
    [ "x$debug" = "x1" ] && echo "oauth_token=${oauth_token:=}"

    eval "${oauth/*&/}"
    [ "x$debug" = "x1" ] && echo "oauth_token_secret=${oauth_token_secret:=}"

    echo "Please open https://launchpad.net/+authorize-token?oauth_token=$oauth_token&allow_permission=DESKTOP_INTEGRATION to authorize the token."

    while :; do
        body=$(http --ignore-stdin --form post https://launchpad.net/+access-token oauth_token="$oauth_token" oauth_consumer_key="$oauth_consumer_key" oauth_signature_method=PLAINTEXT oauth_signature="&$oauth_token_secret")
        if [ "$body" = "Request token has not yet been reviewed. Try again later." ]; then
            sleep 5
        elif [ "$body" = "Invalid OAuth signature." ]; then
            break
        else
            [ "x$debug" = "x1" ] && echo "$body"
            oauth=${body/&lp.context=*/}
            eval "${oauth/&*/}"
            [ "x$debug" = "x1" ] && echo "oauth_token=${oauth_token}"

            eval "${oauth/*&/}"
            [ "x$debug" = "x1" ] && echo "oauth_token_secret=${oauth_token_secret}"
            break
        fi
    done
}

get_api()
{
    api="$1" && shift
    http --ignore-stdin --follow GET "https://api.launchpad.net/$api" \
        'OAuth realm'=="https://api.launchpad.net/" \
        oauth_consumer_key=="${oauth_consumer_key}" \
        oauth_nonce=="$(date +%s)" \
        oauth_signature=="&${oauth_token_secret}" \
        oauth_signature_method=="PLAINTEXT" \
        oauth_timestamp=="$(date +%s)" \
        oauth_token=="${oauth_token}" \
        oauth_version=="1.0" \
        "$@"
}

post_api()
{
    api="$1" && shift
    http --ignore-stdin --form POST "https://api.launchpad.net/$api" \
        'OAuth realm'="https://api.launchpad.net/" \
        oauth_consumer_key="${oauth_consumer_key}" \
        oauth_nonce="$(date +%s)" \
        oauth_signature="&${oauth_token_secret}" \
        oauth_signature_method="PLAINTEXT" \
        oauth_timestamp="$(date +%s)" \
        oauth_token="${oauth_token}" \
        oauth_version="1.0" \
        "$@"
}


if valid_oem_scripts_config; then
    oauth_token=$(read_oem_scripts_config oauth_token)
    oauth_token_secret=$(read_oem_scripts_config oauth_token_secret)
    oauth_consumer_key=$(read_oem_scripts_config oauth_consumer_key)
else
    get_token
    write_oem_scripts_config oauth_token "${oauth_token}"
    write_oem_scripts_config oauth_token_secret "${oauth_token_secret}"
    write_oem_scripts_config oauth_consumer_key "${oauth_consumer_key}"
fi

case "$1" in
    ("get"|"GET")
        shift
        get_api "$@"
        ;;
    ("post"|"POST")
        shift
        post_api "$@"
        ;;
    ("debug")
        debug=1
        get_api devel/people/+me
        ;;
    (*)
        ;;
esac
