#!/bin/bash

if [ -z "$1" ] || ! [[ "$1" =~ ^[1-9][0-9]*$ ]]; then
    cat <<ENDLINE
Usage: $0 [bug id]
A little tool to download all attachments on the bug into lp[bug id] folder.
Ex. \`$0 1\` will download all attachments of bug #1 into the 'lp1' folder.
ENDLINE
    exit 0
fi

JSON="$(mktemp -d)_lp$1.json"

cleanup() {
    rm -f "$JSON"
}
trap cleanup EXIT INT TERM

mkdir -p "lp$1"
cd "lp$1" || exit 1
launchpad-api get bugs/"$1" > "$JSON"

if [ "$(jq -r .information_type < "$JSON")" = 'Public' ]; then
    jq-lp .attachments_collection_link < "$JSON" | jq -r '.entries | .[] | .data_link' | while read -r link; do wget -q --show-progress --content-disposition "$link"; done
else
    jq-lp .attachments_collection_link < "$JSON" | jq -r '.entries | .[] | .data_link + "|" + .title' | while IFS='|' read -r link filename; do launchpad-api get "$link" --print '' --download --output "$filename"; done
fi
