#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

export LAUNCHPAD_API="https://api.staging.launchpad.net/"
export COPYRIGHT_YEAR=2021

# Change the working folder to avoid reading the template files under the source code folder.
cd /tmp

cat > fossa-varys.json <<ENDLINE
{
  "group": "",
  "metabug": 1908047,
  "mirbug": 1937243,
  "platform": "varys",
  "productnames": [
    "Precision 5550"
  ],
  "project": "somerville"
}
ENDLINE

cleanup() {
    echo "= cleanup ="
    if [ -f "bugid" ]; then
        BUG_ID=$(cat bugid)
        rm bugid
    fi
    if [ -f "$BUG_ID.json" ]; then
        jq -S -M < "$BUG_ID.json"
        rm "$BUG_ID.json"
        lp-bug cleanup --yes "$BUG_ID"
    fi
}

trap cleanup EXIT INT TERM

bootstrap-meta create-sru-bug fossa-varys.json --kernel linux-oem-20.04 --output bugid
BUG_ID=$(cat bugid)
lp-api get "bugs/$BUG_ID" > "$BUG_ID.json"
jq -r .description < "$BUG_ID.json" | grep "Precision 5550"
jq -r .description < "$BUG_ID.json" | grep linux-oem-20.04
jq -r '.tags|join(" ")' < "$BUG_ID.json" | grep oem-meta-packages

if bootstrap-meta create-sru-bug fossa-varys.json --kernel linux-oem-20.04 --output bugid; then
    echo "It is expected to return failed."
    exit 1
fi

bootstrap-meta update-sru-bug fossa-varys.json --kernel linux-oem-20.04b --yes
lp-api get "bugs/$BUG_ID" > "$BUG_ID.json"
jq -r .description < "$BUG_ID.json" | grep linux-oem-20.04b

bootstrap-meta update-sru-bug fossa-varys.json --kernel linux-oem-20.04c --yes --ready
lp-api get "bugs/$BUG_ID" > "$BUG_ID.json"
jq -r .description < "$BUG_ID.json" | grep linux-oem-20.04c
jq -r '.tags|join(" ")' < "$BUG_ID.json" | grep oem-needs-upload

bootstrap-meta update-sru-bug fossa-varys.json --kernel linux-generic-hwe-20.04 --yes --release
lp-api get "bugs/$BUG_ID" > "$BUG_ID.json"
jq -r .description < "$BUG_ID.json" | grep linux-generic-hwe-20.04
jq -r '.tags|join(" ")' < "$BUG_ID.json" | grep oem-done-upload

if bootstrap-meta update-sru-git fossa-varys.json --kernel linux-oem-20.04d --dryrun; then
    echo "It is expected to return failed."
    exit 1
fi

bootstrap-meta update-sru-git fossa-varys.json --kernel linux-generic-hwe-20.04 --dryrun
