#!/bin/bash

exec 2>&1
set -euo pipefail
IFS=$'\n\t'

CONDITIONS=("" "https://api.launchpad.net/" "https://api.staging.launchpad.net/")

for VALUE in "${CONDITIONS[@]}"; do
    if [ -n "$VALUE" ]; then
        export LAUNCHPAD_API="$VALUE"
    else
        unset LAUNCHPAD_API
    fi
    printenv | grep LAUNCHPAD_API || echo "There is no LAUNCHPAD_API."

    RET=$(get-private-ppa ppa:oem-solutions-group/ppa)

    if [ "$(echo "$RET" | awk '{print $1}')" != "oem-solutions-group-ubuntu-ppa" ]; then
        if [ -z "${LAUNCHPAD_API:-}" ]; then
            echo "ERR: get-private-ppa ppa:oem-solutions-group/ppa"
        else
            echo "ERR: get-private-ppa ppa:oem-solutions-group/ppa against ${LAUNCHPAD_API}"
        fi
        exit 1
    fi

    # ppa:oem-solutions-group/ppa is a private PPA
    # The output of `get-private-ppa ppa:oem-solutions-group/ppa` contains some credentials.
    # So it avoids checking the part of `echo "$RET" | awk '{print $2}'` here.

    if [ "$(echo "$RET" | awk '{print $3}')" != "7B85BB3BB81D9DAFF9F06250B52B913A41086767" ]; then
        if [ -z "${LAUNCHPAD_API:-}" ]; then
            echo "ERR: get-private-ppa ppa:oem-solutions-group/ppa"
        else
            echo "ERR: get-private-ppa ppa:oem-solutions-group/ppa against ${LAUNCHPAD_API}"
        fi
        exit 1
    fi

    # Just make sure the return code of the following command is OK.
    get-private-ppa ppa:oem-solutions-group/ppa -g > /dev/null

    # ppa:canonical-kernel-team/ppa is a public PPA so there is no credentials in the output.
    if [ "$(get-private-ppa ppa:canonical-kernel-team/ppa)" != "canonical-kernel-team-ubuntu-ppa http://ppa.launchpad.net/canonical-kernel-team/ppa/ubuntu 110E21D8B0E2A1F0243AF6820856F197B892ACEA" ]; then
        if [ -z "${LAUNCHPAD_API:-}" ]; then
            echo "ERR: get-private-ppa canonical-kernel-team/ppa"
        else
            echo "ERR: get-private-ppa canonical-kernel-team/ppa against ${LAUNCHPAD_API}"
        fi
        exit 1
    fi

    # Just make sure the return code of the following command is OK.
    get-private-ppa ppa:canonical-kernel-team/ppa -g > /dev/null
done

exit
