#!/bin/bash

export LAUNCHPAD_TOKEN="::"

if [ "$(launchpad-api get bugs/1 | jq-lp .self_link | jq -r .date_created)" != "2004-08-20T00:00:00+00:00" ]; then
    exit 1
fi

if [ "$(launchpad-api get bugs/1 | jq-lp .self_link | jq-lp .self_link | jq -r .date_created)" != "2004-08-20T00:00:00+00:00" ]; then
    exit 1
fi

exit
