#!/bin/bash

if [ "$(launchpad-api get https://api.launchpad.net/devel/bugs/1 | jq -r .date_created)" != "2004-08-20T00:00:00+00:00" ]; then
    exit 1
fi

if [ "$(launchpad-api get devel/bugs/1 | jq -r .date_created)" != "2004-08-20T00:00:00+00:00" ]; then
    exit 1
fi

if [ "$(launchpad-api get /devel/bugs/1 | jq -r .date_created)" != "2004-08-20T00:00:00+00:00" ]; then
    exit 1
fi

if [ "$(launchpad-api get /bugs/1 | jq -r .date_created)" != "2004-08-20T00:00:00+00:00" ]; then
    exit 1
fi

if [ "$(launchpad-api get bugs/1 | jq -r .date_created)" != "2004-08-20T00:00:00+00:00" ]; then
    exit 1
fi

exit
