#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

export LAUNCHPAD_API="https://api.staging.launchpad.net/"

# Search for the latest bug to test.
while read -r bug; do
    id=$(basename "$bug")
    case "$id" in
        (1943233|1943231|1843358|1830578)
            if ! lp-bug cqa-verify --dry-run "$id"; then
                true
            else
                false
            fi
            ;;
        (*)
            lp-bug cqa-verify --dry-run "$id"
            ;;
    esac
    break
done < <(lp-api get cloudberry ws.op==searchTasks status=="Fix Committed" tags==cqa-verified-staging | jq -r '.entries | .[] | .bug_link' | sort -r)
