#!/bin/bash

cat >/etc/apt/preferences.d/proposed-updates <<EOF
# Configure apt to allow selective installs of packages from proposed
Package: *
Pin: release a=$(lsb_release -cs)-proposed
Pin-Priority: 400
EOF

cat >/etc/apt/sources.list.d/ubuntu-"$(lsb_release -cs)"-proposed.list <<EOF
# Enable Ubuntu proposed archive
deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-proposed restricted main multiverse universe
EOF

apt-get update

mir_bug_verify()
{
    local meta="$1"
    local yaml="$2"
    local old=""
    local new=""
    echo "- meta: $meta" >> "$yaml"

    while read -r _ version url; do
        { echo "  old:"; echo "    version: $version"; echo "    url: $url"; } >> "$yaml"
        old="$version"
    done < <(pkg-list --long "$meta" | grep ^"$meta")
    apt-get install "$meta" --yes
    apt-get update
    apt-get full-upgrade --yes
    apt-get update

    while read -r _ version url; do
        { echo "  new:"; echo "    version: $version"; echo "    url: $url"; } >> "$yaml"
        new="$version"
    done < <(pkg-list --long "$meta" | grep ^"$meta")
    apt-get autopurge "$meta" --yes
    apt-get update
    if dpkg --compare-versions "$old" lt "$new"; then
        echo "  pass: true" >> "$yaml"
    else
        echo "  pass: false" >> "$yaml"
    fi
}

:> "$AUTOPKGTEST_ARTIFACTS"/qemu.yml
mir_bug_verify oem-qemu-meta "$AUTOPKGTEST_ARTIFACTS"/qemu.yml
echo "  bug: null" >> "$AUTOPKGTEST_ARTIFACTS"/qemu.yml

LAUNCHPAD_TOKEN="::" mir-bug collect --ubuntu-certified --verification-needed "$AUTOPKGTEST_ARTIFACTS"/verification-needed.json

:> "$AUTOPKGTEST_ARTIFACTS"/mir-bug-verification.yml
while read -r bug _ meta; do
    echo "Checking $meta for $bug ..."
    mir_bug_verify "$meta" "$AUTOPKGTEST_ARTIFACTS"/mir-bug-verification.yml
    echo "  bug: $bug" >> "$AUTOPKGTEST_ARTIFACTS"/mir-bug-verification.yml
done < <(jq -r '.[] | [.bug, .title] | join(" ")' < "$AUTOPKGTEST_ARTIFACTS"/verification-needed.json)
