#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

export LAUNCHPAD_API="https://api.staging.launchpad.net/"

# check & update
cat > "$AUTOPKGTEST_ARTIFACTS"/fossa-tentacool.json <<ENDLINE
{
  "certification-hardware": [
    "202112-29761",
    "202112-29762",
    "202112-29763",
    "202112-29800",
    "202112-29801",
    "202112-29802"
  ],
  "certify-planning": [
    1942334
  ],
  "metabug": 1942333,
  "mirbug": 1943413,
  "productnames": [
    "XPS 9320"
  ]
}
ENDLINE

export COPYRIGHT_YEAR=2022

# check/update
mir-bug update --yes --skip --ready --release "$AUTOPKGTEST_ARTIFACTS"/fossa-tentacool.json
mir-bug check --skip --ready --release "$AUTOPKGTEST_ARTIFACTS"/fossa-tentacool.json
mir-bug update --yes --skip --tz=UTC --release "$AUTOPKGTEST_ARTIFACTS"/fossa-tentacool.json
mir-bug check --skip --tz=UTC --release "$AUTOPKGTEST_ARTIFACTS"/fossa-tentacool.json

# create
mir-bug create -o bug_id somerville bronn "some Dell platforms"
BUG_ID=$(cat bug_id)
lp-bug cleanup --yes "$BUG_ID"
rm bug_id

# collect
mir-bug collect "$AUTOPKGTEST_ARTIFACTS"/oem-meta-mir-bugs.json
mir-bug collect --ubuntu-certified "$AUTOPKGTEST_ARTIFACTS"/oem-meta-mir-bugs-ubuntu-certified.json
