#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

export LAUNCHPAD_API="https://api.staging.launchpad.net/"

# create
mir-bug create -o bug_id somerville bronn "some Dell platforms"
BUG_ID=$(cat bug_id)
lp-bug cleanup --yes "$BUG_ID"
rm bug_id

# collect
mir-bug collect "$AUTOPKGTEST_ARTIFACTS"/oem-meta-mir-bugs.json
mir-bug collect --ubuntu-certified "$AUTOPKGTEST_ARTIFACTS"/oem-meta-mir-bugs-ubuntu-certified.json

# check & update
cat > fossa-gendry.json <<ENDLINE
{
  "certification-hardware": [
    "202004-27810",
    "202004-27811",
    "202004-27812",
    "202004-27813",
    "202004-27814",
    "202004-27817",
    "202004-27818"
  ],
  "certify-planning": [
    1902620,
    1902621
  ],
  "hardware": [],
  "metabug": 1905527,
  "mirbug": 1932559,
  "productnames": [
    "Precision 7550",
    "Precision 7750"
  ]
}
ENDLINE
mir-bug update --yes --skip --ready fossa-gendry.json

mir-bug check --skip --ready fossa-gendry.json

mir-bug update --yes --skip --tz=UTC fossa-gendry.json

mir-bug check --skip --tz=UTC fossa-gendry.json

exit 77
