#!/bin/sh

cd "$AUTOPKGTEST_ARTIFACTS" || exit 1

export LAUNCHPAD_API="https://api.launchpad.net/"
RET=0

# list
oem-meta-packages --quiet list

# collect
oem-meta-packages --series focal --quiet collect oem-somerville-tentacool-meta
if [ "$(jq -r '."oem-somerville-tentacool-meta".oem.git.kernel_meta' < oem-somerville-tentacool-meta.json)" != "linux-generic-hwe-20.04" ]; then
    echo "FAIL: 'oem-meta-packages --series focal --quiet collect oem-somerville-tentacool-meta' failed."
    RET=1
fi

oem-meta-packages --series jammy --quiet collect oem-somerville-tentacool-meta
if [ "$(jq -r '."oem-somerville-tentacool-meta".oem.git.kernel_meta' < oem-somerville-tentacool-meta.json)" != "linux-generic-hwe-22.04" ]; then
    echo "FAIL: 'oem-meta-packages --series jammy --quiet collect oem-somerville-tentacool-meta' failed."
    RET=1
fi

oem-meta-packages --series focal --quiet collect oem-stella.cmit-camerupt-meta
if [ "$(jq -r '."oem-stella.cmit-camerupt-meta".oem.devel.archive' < oem-stella.cmit-camerupt-meta.json)" != "cesg:stella-cmit-ouagadougou-focal-devel" ]; then
    echo "FAIL: 'oem-meta-packages --series focal --quiet collect oem-stella.cmit-camerupt-meta' failed."
    RET=1
fi

oem-meta-packages --series jammy --quiet collect oem-stella-aron-meta
if [ "$(jq -r '."oem-stella-aron-meta".oem.devel.archive' < oem-stella-aron-meta.json)" != "cesg:stella-jammy-devel" ]; then
    echo "FAIL: 'oem-meta-packages --series jammy --quiet collect oem-stella-aron-meta' failed."
    RET=1
fi

# update
oem-meta-packages --dry-run --series focal update oem-somerville-tentacool-meta
oem-meta-packages --dry-run --series focal update oem-stella.cmit-camerupt-meta
oem-meta-packages --dry-run --series jammy update oem-somerville-tentacool-meta
oem-meta-packages --dry-run --series jammy update oem-stella-aron-meta

# staging-copy
oem-meta-packages --dry-run --series focal staging-copy oem-somerville-kingdra-adl-meta 2>&1 | grep -e cesg:somerville-fossa-kingdra-adl-focal-staging -e somerville-fossa-kingdra-adl-focal-devel
oem-meta-packages --dry-run --series focal staging-copy oem-somerville-charmander-meta 2>&1 | grep -e cesg:somerville-fossa-charmander-focal-staging -e cesg:somerville-fossa-charmander-focal-devel
oem-meta-packages --dry-run --series focal staging-copy oem-stella.cmit-aerodactyl-meta 2>&1 | grep -e cesg:stella-cmit-ouagadougou-focal-staging -e stella-cmit-ouagadougou-focal-devel
oem-meta-packages --dry-run --series focal staging-copy oem-sutton.newell-aaden-meta 2>&1 | grep -e cesg:sutton-newell-focal-staging -e cesg:sutton-newell-focal-devel
oem-meta-packages --dry-run --series jammy staging-copy oem-somerville-tentacool-meta 2>&1 | grep -e cesg:somerville-jellyfish-tentacool-jammy-devel -e cesg:somerville-jellyfish-tentacool-jammy-staging
oem-meta-packages --dry-run --series jammy staging-copy oem-sutton-balesego-meta 2>&1 | grep -e cesg:sutton-jammy-devel -e cesg:sutton-jammy-staging

exit "$RET"
