#!/bin/bash

exec 2>&1
set -euo pipefail
IFS=$'\n\t'

export DEBFULLNAME="Commercial Engineering"
export DEBEMAIL="commercial-engineering@canonical.com"

pkg-stella-meta --public-bug 1895517 --private-bug 1892301 -s focal -k linux-oem-20.04 -g cmit -p ivysaur 8750

cd oem-stella.cmit-ivysaur-meta || exit 1

git checkout cmit.ivysaur-focal-ubuntu

grep "^deb http://hp.archive.canonical.com/ focal stella$" oem-stella.cmit-ivysaur-meta.list
grep "^# deb-src http://hp.archive.canonical.com/ focal stella$" oem-stella.cmit-ivysaur-meta.list
grep "^deb http://hp.archive.canonical.com/ focal stella.cmit$" oem-stella.cmit-ivysaur-meta.list
grep "^# deb-src http://hp.archive.canonical.com/ focal stella.cmit$" oem-stella.cmit-ivysaur-meta.list

grep "oem-stella.cmit-ivysaur-meta (20.04~ubuntu1) UNRELEASED; urgency=medium" debian/changelog
grep "\* Meta package for Stella Cmit Ivysaur." debian/changelog
grep '(LP: #1895517)' debian/changelog

grep "Source: oem-stella.cmit-ivysaur-meta" debian/control
grep "Package: oem-stella.cmit-ivysaur-meta" debian/control
grep -v "Package: oem-stella.cmit-factory-ivysaur-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "^Restrictions: needs-root$" debian/tests/control
grep "^apt-get autoremove --purge --yes oem-stella.cmit-ivysaur-meta$" debian/tests/meta

grep "Upstream-Name: oem-stella.cmit-ivysaur-meta" debian/copyright

grep "alias pci:\*sv0000103Csd00008750bc0Csc05\* meta oem-stella.cmit-ivysaur-meta" debian/modaliases

git checkout cmit.ivysaur-focal-oem

grep "^deb http://hp.archive.canonical.com/ focal stella$" oem-stella.cmit-ivysaur-meta.list
grep "^# deb-src http://hp.archive.canonical.com/ focal stella$" oem-stella.cmit-ivysaur-meta.list
grep "^deb http://hp.archive.canonical.com/ focal stella.cmit$" oem-stella.cmit-ivysaur-meta.list
grep "^# deb-src http://hp.archive.canonical.com/ focal stella.cmit$" oem-stella.cmit-ivysaur-meta.list

grep "oem-stella.cmit-ivysaur-meta (20.04ubuntu1) focal; urgency=medium" debian/changelog
grep "\* Meta package for Stella Cmit Ivysaur." debian/changelog
grep '(LP: #1892301)' debian/changelog

grep "Source: oem-stella.cmit-ivysaur-meta" debian/control
grep "Package: oem-stella.cmit-factory-ivysaur-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring, linux-oem-20.04, oem-stella.cmit-meta" debian/control
grep "Depends: \${misc:Depends}, oem-stella.cmit-factory-meta" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "^Restrictions: needs-root$" debian/tests/control
grep "^apt-get autoremove --purge --yes oem-stella.cmit-ivysaur-meta$" debian/tests/meta

grep "Upstream-Name: oem-stella.cmit-ivysaur-meta" debian/copyright

grep "alias pci:\*sv0000103Csd00008750bc0Csc05\* meta oem-stella.cmit-ivysaur-meta" debian/modaliases
