#!/bin/bash

exec 2>&1
set -euo pipefail
IFS=$'\n\t'

export DEBFULLNAME="Commercial Engineering"
export DEBEMAIL="commercial-engineering@canonical.com"

pkg-somerville-meta --public-bug 1868254 --private-bug 123456 -s focal -k oem -p three-eyed-raven 0962

cd oem-somerville-three-eyed-raven-meta || exit 1

git checkout three-eyed-raven-focal-ubuntu

grep "^deb http://dell.archive.canonical.com/ focal somerville\$" oem-somerville-three-eyed-raven-meta.list
grep "^# deb-src http://dell.archive.canonical.com/ focal somerville\$" oem-somerville-three-eyed-raven-meta.list
grep "^deb http://dell.archive.canonical.com/ focal somerville-three-eyed-raven\$" oem-somerville-three-eyed-raven-meta.list
grep "^# deb-src http://dell.archive.canonical.com/ focal somerville-three-eyed-raven\$" oem-somerville-three-eyed-raven-meta.list

grep "oem-somerville-three-eyed-raven-meta (20.04~ubuntu1) focal; urgency=medium" debian/changelog
grep "Meta package for Somerville Three-Eyed-Raven." debian/changelog
grep '(LP: #1868254)' debian/changelog

grep "Source: oem-somerville-three-eyed-raven-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring$" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep -v "Package: oem-somerville-factory-three-eyed-raven-meta" debian/control

grep "Upstream-Name: oem-somerville-three-eyed-raven-meta" debian/copyright

grep "alias pci:\*sv00001028sd00000962\* meta oem-somerville-three-eyed-raven-meta" debian/modaliases

grep "^pristine-tar = False$" debian/gbp.conf
grep "^debian-branch=three-eyed-raven-focal-ubuntu$" debian/gbp.conf

git checkout three-eyed-raven-focal-oem

grep "^deb http://dell.archive.canonical.com/ focal somerville\$" oem-somerville-three-eyed-raven-meta.list
grep "^# deb-src http://dell.archive.canonical.com/ focal somerville\$" oem-somerville-three-eyed-raven-meta.list
grep "^deb http://dell.archive.canonical.com/ focal somerville-three-eyed-raven\$" oem-somerville-three-eyed-raven-meta.list
grep "^# deb-src http://dell.archive.canonical.com/ focal somerville-three-eyed-raven\$" oem-somerville-three-eyed-raven-meta.list

grep "oem-somerville-three-eyed-raven-meta (20.04ubuntu1) focal; urgency=medium" debian/changelog
grep "Meta package for Somerville Three-Eyed-Raven." debian/changelog
grep '(LP: #123456)' debian/changelog

grep "Source: oem-somerville-three-eyed-raven-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring, linux-oem-20.04, oem-somerville-meta$" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "Package: oem-somerville-factory-three-eyed-raven-meta" debian/control
grep "Depends: \${misc:Depends}, oem-somerville-factory-meta$" debian/control

grep "Upstream-Name: oem-somerville-three-eyed-raven-meta" debian/copyright

grep "alias pci:\*sv00001028sd00000962\* meta oem-somerville-three-eyed-raven-meta" debian/modaliases

grep "^pristine-tar = False$" debian/gbp.conf
grep "^debian-branch=three-eyed-raven-focal-oem$" debian/gbp.conf

cd ..
rm -fr oem-somerville-three-eyed-raven-meta

pkg-somerville-meta --public-bug 1868254 --private-bug 123456 -s focal -k default -p three-eyed-raven 0962

cd oem-somerville-three-eyed-raven-meta || exit 1

git checkout three-eyed-raven-focal-ubuntu
grep "XB-Ubuntu-OEM-Kernel-Flavour: default" debian/control

git checkout three-eyed-raven-focal-oem
grep "XB-Ubuntu-OEM-Kernel-Flavour: default" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring, linux-generic-hwe-20.04, oem-somerville-meta$" debian/control
