#!/bin/bash

echo "=== Enable focal proposed channel ==="
APTDIR=$(setup-apt-dir.sh -c focal -m http://uk.archive.ubuntu.com/ubuntu -p | tail -n1)

echo "=== ubuntu-desktop --recommends ==="
pkg-list --apt-dir "$APTDIR" ubuntu-desktop --recommends | tee ubuntu-desktop.list
if ! pkg-list --apt-dir "$APTDIR" ubuntu-desktop --recommends --fail-unavailable; then
    echo "It is usual to see some Debian package still unavailable in proposed channel."
fi

echo "=== dkms ==="
pkg-list --apt-dir "$APTDIR" dkms --exclude ubuntu-desktop.list | tee dkms.list

cat ubuntu-desktop.list dkms.list > all.list

echo "=== nvidia-settings nvidia-prime nvidia-driver-455 ==="
pkg-list --apt-dir "$APTDIR" nvidia-settings nvidia-prime nvidia-driver-455 --exclude all.list

echo "=== linux-generic ==="
pkg-list --apt-dir "$APTDIR" linux-generic --exclude all.list

echo "=== linux-generic-hwe-20.04 ==="
pkg-list --apt-dir "$APTDIR" linux-generic-hwe-20.04 --exclude all.list

echo "=== linux-oem-20.04 ==="
pkg-list --apt-dir "$APTDIR" linux-oem-20.04 --exclude all.list

rm -fr "$APTDIR"

echo "=== oem-scripts ==="
APTDIR=$(setup-apt-dir.sh -c focal -m http://uk.archive.ubuntu.com/ubuntu -p --ppa ppa:oem-solutions-engineers/pc-enablement-tools | tail -n1)
pkg-list --verbose oem-scripts --apt-dir "$APTDIR" --exclude all.list

rm -fr "$APTDIR"
