#!/bin/bash

exec 2>&1
set -euo pipefail
IFS=$'\n\t'

export DEBFULLNAME="Commercial Engineering"
export DEBEMAIL="commercial-engineering@canonical.com"

echo "== Check oem-lyoncore-meta =="

pkg-iot-meta --series=jammy --project-name=lyoncore

cd oem-lyoncore-meta || exit 1

git checkout lyoncore-jammy

grep "^deb http://lyoncore.archive.canonical.com/ jammy lyoncore$" oem-lyoncore-meta.list
grep "^# deb-src http://lyoncore.archive.canonical.com/ jammy lyoncore$" oem-lyoncore-meta.list

grep "oem-lyoncore-meta (22.04ubuntu1) jammy; urgency=medium" debian/changelog
grep "\* Meta package for lyoncore project." debian/changelog

grep "Source: oem-lyoncore-meta" debian/control
grep "Build-Depends: debhelper-compat (= 12), config-package-dev (>= 5.0)" debian/control
grep "Package: oem-lyoncore-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring" debian/control
grep "^Restrictions: needs-root$" debian/tests/control

grep "^apt-get autoremove --purge --yes oem-lyoncore-meta$" debian/tests/meta

grep "Upstream-Name: oem-lyoncore-meta" debian/copyright

grep "dh \$@ --with config-package$" debian/rules

grep "[DEFAULT]" release-upgrades.oem
grep "Prompt=never" release-upgrades.oem

grep "/etc/update-manager/release-upgrades\.oem" debian/displace
grep "\.oem" debian/displace-extension

cd ..
rm -fr oem-lyoncore-meta
