#!/bin/bash

exec 2>&1
set -euo pipefail
IFS=$'\n\t'

export DEBFULLNAME="Commercial Engineering"
export DEBEMAIL="commercial-engineering@canonical.com"

echo "== Check linux-oem-24.04 =="

pkg-sutton-meta --public-bug 123456 --private-bug 1874177 -s noble -k linux-oem-24.04 -p AdaM N2U bvnLENOVo:bvrN2o

cd oem-sutton-adam-meta || exit 1

git checkout adam-noble-ubuntu

grep "^deb http://lenovo.archive.canonical.com/ noble sutton$" oem-sutton-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ noble sutton$" oem-sutton-adam-meta.list
grep -v "^deb http://lenovo.archive.canonical.com/ noble sutton.newell$" oem-sutton-adam-meta.list
grep -v "^# deb-src http://lenovo.archive.canonical.com/ noble sutton.newell$" oem-sutton-adam-meta.list
grep "^deb http://lenovo.archive.canonical.com/ noble sutton-adam$" oem-sutton-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ noble sutton-adam$" oem-sutton-adam-meta.list

grep "oem-sutton-adam-meta (24.04~ubuntu1) UNRELEASED; urgency=medium" debian/changelog
grep "\* Meta package for Sutton Adam." debian/changelog
grep '(LP: #123456)' debian/changelog

grep "Source: oem-sutton-adam-meta" debian/control
grep "Package: oem-sutton-adam-meta" debian/control
grep -v "Package: oem-sutton-factory-adam-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "^Restrictions: needs-root$" debian/tests/control
grep "^apt-get autoremove --purge --yes oem-sutton-adam-meta$" debian/tests/meta

grep "Upstream-Name: oem-sutton-adam-meta" debian/copyright

grep "alias dmi:\*bvnLENOVO:bvrN2U\* meta oem-sutton-adam-meta" debian/modaliases
grep "alias dmi:\*bvnLENOVO:bvrN2O\* meta oem-sutton-adam-meta" debian/modaliases

# oem-flavour.cfg only exists in oem branch.
if [ -f oem-flavour.cfg ]; then
    exit 1
fi

git checkout adam-noble-oem

grep "^deb http://lenovo.archive.canonical.com/ noble sutton$" oem-sutton-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ noble sutton$" oem-sutton-adam-meta.list
grep -v "^deb http://lenovo.archive.canonical.com/ noble sutton.newell$" oem-sutton-adam-meta.list
grep -v "^# deb-src http://lenovo.archive.canonical.com/ noble sutton.newell$" oem-sutton-adam-meta.list
grep "^deb http://lenovo.archive.canonical.com/ noble sutton-adam$" oem-sutton-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ noble sutton-adam$" oem-sutton-adam-meta.list

grep "oem-sutton-adam-meta (24.04ubuntu1) noble; urgency=medium" debian/changelog
grep "\* Meta package for Sutton Adam." debian/changelog
grep '(LP: #1874177)' debian/changelog

grep "Source: oem-sutton-adam-meta" debian/control
grep "Package: oem-sutton-factory-adam-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring, linux-oem-24.04, oem-sutton-meta" debian/control
grep "Depends: \${misc:Depends}, oem-sutton-factory-meta" debian/control
grep "Suggests: oem-sutton-adam-doc" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "^Restrictions: needs-root$" debian/tests/control
grep "^apt-get autoremove --purge --yes oem-sutton-adam-meta$" debian/tests/meta

grep "Upstream-Name: oem-sutton-adam-meta" debian/copyright

grep "alias dmi:\*bvnLENOVO:bvrN2U\* meta oem-sutton-adam-meta" debian/modaliases
grep "alias dmi:\*bvnLENOVO:bvrN2O\* meta oem-sutton-adam-meta" debian/modaliases

# oem-flavour.cfg only exists in oem branch.
if [ ! -f oem-flavour.cfg ]; then
    exit 1
fi
grep "^GRUB_FLAVOUR_ORDER=oem$" oem-flavour.cfg

cd ..
rm -fr oem-sutton-adam-meta

echo "== Check linux-oem-22.04a =="

pkg-sutton-meta --public-bug 123456 --private-bug 1874177 -s jammy -k linux-oem-22.04a -p AdaM N2U bvnLENOVo:bvrN2o

cd oem-sutton-adam-meta || exit 1

git checkout adam-jammy-ubuntu

grep "^deb http://lenovo.archive.canonical.com/ jammy sutton$" oem-sutton-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ jammy sutton$" oem-sutton-adam-meta.list
grep -v "^deb http://lenovo.archive.canonical.com/ jammy sutton.newell$" oem-sutton-adam-meta.list
grep -v "^# deb-src http://lenovo.archive.canonical.com/ jammy sutton.newell$" oem-sutton-adam-meta.list

grep "oem-sutton-adam-meta (22.04~ubuntu1) UNRELEASED; urgency=medium" debian/changelog
grep "\* Meta package for Sutton Adam." debian/changelog
grep '(LP: #123456)' debian/changelog

grep "Source: oem-sutton-adam-meta" debian/control
grep "Package: oem-sutton-adam-meta" debian/control
grep -v "Package: oem-sutton-factory-adam-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "^Restrictions: needs-root$" debian/tests/control
grep "^apt-get autoremove --purge --yes oem-sutton-adam-meta$" debian/tests/meta

grep "Upstream-Name: oem-sutton-adam-meta" debian/copyright

grep "alias dmi:\*bvnLENOVO:bvrN2U\* meta oem-sutton-adam-meta" debian/modaliases
grep "alias dmi:\*bvnLENOVO:bvrN2O\* meta oem-sutton-adam-meta" debian/modaliases

git checkout adam-jammy-oem

grep "^deb http://lenovo.archive.canonical.com/ jammy sutton$" oem-sutton-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ jammy sutton$" oem-sutton-adam-meta.list
grep -v "^deb http://lenovo.archive.canonical.com/ jammy sutton.newell$" oem-sutton-adam-meta.list
grep -v "^# deb-src http://lenovo.archive.canonical.com/ jammy sutton.newell$" oem-sutton-adam-meta.list

grep "oem-sutton-adam-meta (22.04ubuntu1) jammy; urgency=medium" debian/changelog
grep "\* Meta package for Sutton Adam." debian/changelog
grep '(LP: #1874177)' debian/changelog

grep "Source: oem-sutton-adam-meta" debian/control
grep "Package: oem-sutton-factory-adam-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring, linux-oem-22.04a, oem-sutton-meta" debian/control
grep "Depends: \${misc:Depends}, oem-sutton-factory-meta" debian/control
grep "Suggests: oem-sutton-adam-doc" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "^Restrictions: needs-root$" debian/tests/control
grep "^apt-get autoremove --purge --yes oem-sutton-adam-meta$" debian/tests/meta

grep "Upstream-Name: oem-sutton-adam-meta" debian/copyright

grep "alias dmi:\*bvnLENOVO:bvrN2U\* meta oem-sutton-adam-meta" debian/modaliases
grep "alias dmi:\*bvnLENOVO:bvrN2O\* meta oem-sutton-adam-meta" debian/modaliases

cd ..
rm -fr oem-sutton-adam-meta

echo "== Check linux-oem-20.04 =="

pkg-sutton-meta --public-bug 123456 --private-bug 1874177 -s focal -k linux-oem-20.04 -g Newell -p AdaM N2U bvnLENOVo:bvrN2o

cd oem-sutton.newell-adam-meta || exit 1

git checkout newell.adam-focal-ubuntu

grep "^deb http://lenovo.archive.canonical.com/ focal sutton$" oem-sutton.newell-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ focal sutton$" oem-sutton.newell-adam-meta.list
grep "^deb http://lenovo.archive.canonical.com/ focal sutton.newell$" oem-sutton.newell-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ focal sutton.newell$" oem-sutton.newell-adam-meta.list

grep "oem-sutton.newell-adam-meta (20.04~ubuntu1) UNRELEASED; urgency=medium" debian/changelog
grep "\* Meta package for Sutton Newell Adam." debian/changelog
grep '(LP: #123456)' debian/changelog

grep "Source: oem-sutton.newell-adam-meta" debian/control
grep "Package: oem-sutton.newell-adam-meta" debian/control
grep -v "Package: oem-sutton.newell-factory-adam-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "^Restrictions: needs-root$" debian/tests/control
grep "^apt-get autoremove --purge --yes oem-sutton.newell-adam-meta$" debian/tests/meta

grep "Upstream-Name: oem-sutton.newell-adam-meta" debian/copyright

grep "alias dmi:\*bvnLENOVO:bvrN2U\* meta oem-sutton.newell-adam-meta" debian/modaliases
grep "alias dmi:\*bvnLENOVO:bvrN2O\* meta oem-sutton.newell-adam-meta" debian/modaliases

git checkout newell.adam-focal-oem

grep "^deb http://lenovo.archive.canonical.com/ focal sutton$" oem-sutton.newell-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ focal sutton$" oem-sutton.newell-adam-meta.list
grep "^deb http://lenovo.archive.canonical.com/ focal sutton.newell$" oem-sutton.newell-adam-meta.list
grep "^# deb-src http://lenovo.archive.canonical.com/ focal sutton.newell$" oem-sutton.newell-adam-meta.list

grep "oem-sutton.newell-adam-meta (20.04ubuntu1) focal; urgency=medium" debian/changelog
grep "\* Meta package for Sutton Newell Adam." debian/changelog
grep '(LP: #1874177)' debian/changelog

grep "Source: oem-sutton.newell-adam-meta" debian/control
grep "Package: oem-sutton.newell-factory-adam-meta" debian/control
grep "Depends: \${misc:Depends}, ubuntu-oem-keyring, linux-oem-20.04, oem-sutton.newell-meta" debian/control
grep "Depends: \${misc:Depends}, oem-sutton.newell-factory-meta" debian/control
grep "Suggests: oem-sutton.newell-adam-doc" debian/control
grep "XB-Ubuntu-OEM-Kernel-Flavour: oem" debian/control
grep "^Restrictions: needs-root$" debian/tests/control
grep "^apt-get autoremove --purge --yes oem-sutton.newell-adam-meta$" debian/tests/meta

grep "Upstream-Name: oem-sutton.newell-adam-meta" debian/copyright

grep "alias dmi:\*bvnLENOVO:bvrN2U\* meta oem-sutton.newell-adam-meta" debian/modaliases
grep "alias dmi:\*bvnLENOVO:bvrN2O\* meta oem-sutton.newell-adam-meta" debian/modaliases

cd ..
rm -fr oem-sutton.newell-adam-meta
