#!/bin/bash

export LAUNCHPAD_TOKEN="::"

setup-apt-dir.sh -c jammy -m http://archive.ubuntu.com/ubuntu --disable-updates --disable-backports -o aptdir.log
rm -f aptdir.log
setup-apt-dir.sh -c focal -m http://archive.ubuntu.com/ubuntu --disable-updates --disable-backports -o aptdir.log
if [ ! -e aptdir.log ]; then
    echo "aptdir.log doesn't exist."
    exit 1
fi
APTDIR="$(cat aptdir.log)"

if [ "$(apt-cache -o "Dir=$APTDIR" -o "Dir::State::status=$APTDIR/var/lib/dpkg/status" show linux-generic | grep ^Version)" != "Version: 5.4.0.26.32" ]; then
    echo "It should only find out linux-generic 5.4.0.26.32."
    exit 1
fi

if apt-cache -o "Dir=$APTDIR" -o "Dir::State::status=$APTDIR/var/lib/dpkg/status" show ibus-typing-booster >/dev/null 2>&1; then
    echo "ibus-typing-booster only exists in focal-backports. It should not be found."
    exit 1
fi
rm -fr "$APTDIR" aptdir.log

APTDIR=$(setup-apt-dir.sh -c focal -m http://archive.ubuntu.com/ubuntu -p --ppa ppa:oem-solutions-engineers/pc-enablement-tools | tail -n1)
if [ -n "$APTDIR" ] && [ -d "$APTDIR" ] && [[ "$APTDIR" =~ ^/tmp/apt\. ]]; then
    apt-cache -o "Dir=$APTDIR" -o "Dir::State::status=$APTDIR/var/lib/dpkg/status" policy oem-scripts | grep oem-solutions-engineers/pc-enablement-tools
    rm -fr "$APTDIR"
else
    echo "APTDIR = '$APTDIR' invalid."
    exit 1
fi

setup-apt-dir.sh -c focal -m http://archive.ubuntu.com/ubuntu -p --ppa ppa:oem-solutions-engineers/pc-enablement-tools -o aptdir.log
if [ ! -e aptdir.log ]; then
    echo "aptdir.log doesn't exist."
    exit 1
fi
APTDIR="$(cat aptdir.log)"
if [ -n "$APTDIR" ] && [ -d "$APTDIR" ] && [[ "$APTDIR" =~ ^/tmp/apt\. ]]; then
    apt-cache -o "Dir=$APTDIR" -o "Dir::State::status=$APTDIR/var/lib/dpkg/status" policy oem-scripts | grep oem-solutions-engineers/pc-enablement-tools
    rm -fr "$APTDIR" aptdir.log
else
    echo "APTDIR = '$APTDIR' invalid."
    exit 1
fi

setup-apt-dir.sh -c focal -m http://archive.ubuntu.com/ubuntu --i386 -o aptdir.log
if [ ! -e aptdir.log ]; then
    echo "aptdir.log doesn't exist."
    exit 1
fi
APTDIR="$(cat aptdir.log)"
if [ -n "$APTDIR" ] && [ -d "$APTDIR" ] && [[ "$APTDIR" =~ ^/tmp/apt\. ]]; then
    apt-cache -o "Dir=$APTDIR" -o "Dir::State::status=$APTDIR/var/lib/dpkg/status" policy libc6:i386 | grep libc6:i386
    rm -fr "$APTDIR" aptdir.log
else
    echo "APTDIR = '$APTDIR' invalid."
    exit 1
fi

exit 0
