#!/bin/bash

setup-apt-dir.sh -c focal -m http://archive.ubuntu.com/ubuntu -p --ppa ppa:oem-solutions-engineers/pc-enablement-tools | tee setup.log
APTDIR="$(tail -n1 setup.log)"
if [ -n "$APTDIR" ] && [ -d "$APTDIR" ] && [[ "$APTDIR" =~ ^/tmp/apt\. ]]; then
    apt-cache -o "Dir=$APTDIR" -o "Dir::State::status=$APTDIR/var/lib/dpkg/status" policy oem-scripts | grep oem-solutions-engineers/pc-enablement-tools
    rm -fr "$APTDIR"
else
    echo "APTDIR = '$APTDIR' invalid."
    exit 1
fi

setup-apt-dir.sh -c focal -m http://archive.ubuntu.com/ubuntu -p --ppa ppa:oem-solutions-engineers/pc-enablement-tools -o aptdir.log
if [ ! -e aptdir.log ]; then
    echo "aptdir.log doesn't exist."
    exit 1
fi
APTDIR="$(cat aptdir.log)"
if [ -n "$APTDIR" ] && [ -d "$APTDIR" ] && [[ "$APTDIR" =~ ^/tmp/apt\. ]]; then
    apt-cache -o "Dir=$APTDIR" -o "Dir::State::status=$APTDIR/var/lib/dpkg/status" policy oem-scripts | grep oem-solutions-engineers/pc-enablement-tools
    rm -fr "$APTDIR" aptdir.log
else
    echo "APTDIR = '$APTDIR' invalid."
    exit 1
fi
